server:
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
    accept-count: 1000

  servlet:
    session:
      cookie:
        http-only: true
    context-path: /sms
spring:
  server:
    port: 8080
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq-gjp
    password: rabbitmq-gjp
    publisher-confirms: true
  mail:
    host: smtp.qq.com
    username: 1076730460@qq.com
    password: rmrbqcfriptgjchi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mail:
  from: ${spring.mail.username}
  to: yyyyyy@qq.com
